### ISSUE TITLE
GPS Lat/Long Navigation Not Working

### ISSUE THREAD

**Issue by Latavish** [Kinkkujuustovoileipa/uh-60l#100]
Appears when using the GPS Doppler Navigation in Lat/Long mode is not working. After entering in coordinates - the location it sends you is way off.

**Comment by Jedi1-4** [comment]
Works correctly. may be improper grid format. make sure F10 map is changed to degrees minutes decimal minutes. 128D will not understand degrees minutes seconds. better yet use MGRS to avoid confusion.

**Comment by Kinkkujuustovoileipa** [comment]
Fixed unrelated issue with validation, closing this as seems to be incorrect format used.
