### ISSUE TITLE
HSI course deviation bar error

### ISSUE THREAD

**Issue by Tekada1-0** [Kinkkujuustovoileipa/uh-60l#102]
When getting a from indication and selecting an outbound heading from the station the course deviation bar moves from full scale deflection to full scale deflection.  Cannot select an outbound course correctly.

**Comment by asherao** [comment]
Please try again with v1.1 at a reasonable distance away from the navaid.

**Comment by Tekada1-0** [comment]
[https://www.youtube.com/watch?v=-S89HizBUz0](url)

Course selection/deviation should function regardless of flying towards or away from a VOR nav station.  Example.  When the nav station is behind the aircraft an outbound course should be selectable same as selecting a course inbound.  This is common to any VOR navigation system in most aircraft.  

The error in this system is when attempting to select an outbound course.  The course deviation bar on the HSI swings full deflection with no lateral (no selectable course to navigate on) deviation indication.  In the example video around 030/031 course selection, you can see how the HSI course deviation bar goes from full scale left to full scale right.  It should behave the same way it does when selecting the inbound course.  The inbound course is demonstrated in the video when adjusting the course knob between 200 to 220. 

Ref: Public release TM and many years of flying the UH60 A/L
