### ISSUE TITLE
Radar Altimeter Indications

### ISSUE THREAD

**Issue by ftr784** [Kinkkujuustovoileipa/uh-60l#11]
Radar Altimeter Digital Readout should indicate in 1ft increments from 0-199 ft.   
Radar Altimeter Digital Readout will switch to 10ft increments from 200-1500 ft.  (Ex, 220, 230, 240, etc.)
Above 1500 ft, Radar Altimeter Digital Readout will extinguish and Altitude Pointer will travel behind Dial Mask (i.e., above 1500 ft and out of view).

**Comment by asherao** [comment]
Seems to be fixed. Recommend closing.
