### ISSUE TITLE
Nr (Rotor Speed) not Driven by Np(Engine Speed)

### ISSUE THREAD

**Issue by JRMITCH86** [Kinkkujuustovoileipa/uh-60l#113]
When advancing PCL's the Nr (Rotor Speed) should match the "driven speed" of the Np (Engine Driveshaft Output)

**Comment by Jedi1-4** [comment]
Confirmed. RPMR is remaining above NP from idle to fly.

**Comment by Kinkkujuustovoileipa** [comment]
Won't be perfect but is improved, marking this issue as fixed in 1.2
