### ISSUE TITLE
Roll command bar

### ISSUE THREAD

**Issue by Jedi1-4** [Kinkkujuustovoileipa/uh-60l#115]
When in HDG mode the roll command bar does not give indications to maintain the heading.

**Comment by Kinkkujuustovoileipa** [comment]
Couldn't reproduce this, need more info

**Comment by asherao** [comment]
I also cannot replicate the issue.

**Comment by Jedi1-4** [comment]
Just double checked. Its working correct. Roll command bar just feels too sensitive. Could be my winwing. for reference, the roll command bar should give 1 degree of roll correction for each degree of heading correction up to a max of 20% in roll.
