### ISSUE TITLE
Fuel Quantity Digital Readout on CDI should display in 10 lb increments

### ISSUE THREAD

**Issue by ftr784** [Kinkkujuustovoileipa/uh-60l#12]

**Comment by asherao** [comment]
Fixed.
![image](https://user-images.githubusercontent.com/15984377/150822861-aa69cbd5-8d7c-4f1f-b3e4-0d7507668dd5.png)
![image](https://user-images.githubusercontent.com/15984377/150822916-6afb16e2-29d7-4268-ae68-8ea04f83ec41.png)
