### ISSUE TITLE
[Feature request] Separate key bindings for extending and retracting the fuel probe

### ISSUE THREAD

**Issue by Joghurt** [Kinkkujuustovoileipa/uh-60l#121]
Like with other airplanes I would like to bind the fuel probe to a switch with two states which is not possible at the moment (or to be more precise at the moment it extracts the probe at spawn).

**Comment by asherao** [comment]
This feature can be added by putting the following in `...\Saved Games\DCS.openbeta\mods\aircraft\UH-60L\Input\keyboard\default.lua` directly below the AAR Probe Extend/Retract arround line 342. You can do the same for `\UH-60L\Input\joystick\default.lua`.


> {down = device_commands.fuelProbe, up = device_commands.fuelProbe, cockpit_device_id = devices.EXTLIGHTS, value_down = 1.0, value_up = 0.0, name = _('AAR Probe Extend else Retract'), category = _('General')},
> 
> {down = device_commands.fuelProbe, up = device_commands.fuelProbe, cockpit_device_id = devices.EXTLIGHTS, value_down = 0.0, value_up = 1.0, name = _('AAR Probe 2 '), category = _('General')},
> 
> {down = device_commands.fuelProbe, cockpit_device_id = devices.EXTLIGHTS, value_down = 1.0, value_up = 0.0, name = _('AAR Probe Extend'), category = _('General')},
> 
> {up = device_commands.fuelProbe, cockpit_device_id = devices.EXTLIGHTS, value_down = 1.0, value_up = 0.0, name = _('AAR Probe Retract'), category = _('General')},

**Comment by Joghurt** [comment]
In my oppinion one of the "else"s is totally sufficient. No need to flood the key bindings. ;)

**Comment by asherao** [comment]
Feel free to add any number of those to your game. All of them will likely be added to accommodate the range of controllers people use.
