### ISSUE TITLE
uh-60 hover issue with "Solo Flight" Checked in ME

### ISSUE THREAD

**Issue by TimNeuman** [Kinkkujuustovoileipa/uh-60l#123]
i found a problem with the hover in the helicopter when spawned hot at the ramp with 10% internal fuel, 4 tanks, no probe, solo flight, on any map.
because you need an nose angle of about 15-20° to stay in positio
![Screen_220129_161643](https://user-images.githubusercontent.com/55442555/151666729-c9edfd11-4733-41a0-bb2e-fb67710b696f.png)
![Screen_220129_161652](https://user-images.githubusercontent.com/55442555/151666743-4ef6fa3c-4b1c-4061-b66b-6e8ae3bf417f.png)
n

**Comment by asherao** [comment]
About a 12ft hover. No issue found so far. Please send miz and short track if you can.
![image](https://user-images.githubusercontent.com/15984377/151668355-4f903949-81ce-4326-af95-558bed69018a.png)
[uh60hover.zip](https://github.com/Kinkkujuustovoileipa/uh-60l/files/7964076/uh60hover.zip)

**Comment by TimNeuman** [comment]
>
[UH-60 hover vid.zip](https://github.com/Kinkkujuustovoileipa/uh-60l/files/7964137/UH-60.hover.vid.zip)

**Comment by asherao** [comment]
> [UH-60 test.zip](https://github.com/Kinkkujuustovoileipa/uh-60l/files/7964159/UH-60.test.zip) [UH-60 hover vid.zip](https://github.com/Kinkkujuustovoileipa/uh-60l/files/7964171/UH-60.hover.vid.zip)

Issue replicated with attached miz
Difference may be in ground hot vs. ramp hot

**Comment by asherao** [comment]
Confirmed problem when "Solo Flight" is checked in ME.
