### ISSUE TITLE
Pedal authority is too strong

### ISSUE THREAD

**Issue by admiki** [Kinkkujuustovoileipa/uh-60l#126]
Flying straight and level at 120 knots, pushing full pedal on either side will cause tail to go past 90° perpendicular to flight direction.
I don't have exact numbers for UH60, but most helicopters I know of can't go past 40-50 knots in sideways flight.
Only number I have is required authority for 15°/sec at 35 knots 
https://www.sikorskyarchives.com/S-70%20(YUH-60A%20UTTAS).PHP

**Comment by admiki** [comment]
Contacted former IRL UH60 pilot. Sideways flight limit was 45 knots. He also does not know how much UH60 could push its tail sideways, but he is also sure it's not 120 knots

**Comment by clutchtomcat** [comment]
Shouldn't pedal input be dampened above 80kts?

**Comment by Kinkkujuustovoileipa** [comment]
Fixed 1.2

**Comment by AASLT-Hawker** [comment]
> Contacted former IRL UH60 pilot. Sideways flight limit was 45 knots. He also does not know how much UH60 could push its tail sideways, but he is also sure it's not 120 knots

45kts is just the operator's limitation and does not reflect what the aicraft is cabable of doing.

**Comment by AASLT-Hawker** [comment]
> Shouldn't pedal input be dampened above 80kts?

Should not. You are probably referring to an operator's limitation of  "avoid full pedal inputs above 80kts". Does not mean the tail rotor is dampened above 80kts.
