### ISSUE TITLE
guages go out below 95% r/rpm when shutting down

### ISSUE THREAD

**Issue by CarlBevan** [Kinkkujuustovoileipa/uh-60l#128]
in the 1.1 update after landing, when shutting down the machine you roll throttle back to idle and the r/rpm comes down below 95% all the illuminated gauges on the center console eg. radios/stab system go out. If you roll the throttle back on and rpm goes up then they come back on.

**Comment by asherao** [comment]
Please explain the expected behavior.

**Comment by CarlBevan** [comment]
Ok just tried it again. From a cold start if you start as normal all switches, radios etc and then get to 100% r/rpm basically ready to fly. Wind off the throttles to idle and you will see that once R/rpm goes below 95% the R/rpm guage turns off and all centre panel guages/radios turn off. Put the throttle back to full and everything comes back on once over 95% R/rpm. I dont think this is normal as if on the ground and you went to idle to say wait for pax to load into the machine, power to the radios/r/rpm guage etc would stil stay on

**Comment by Tekada1-0** [comment]
Did you have the APU running and APU generator on?

**Comment by CarlBevan** [comment]
I had turned those off after start up. I tried it with them on and had same thing. Also noticed the warning lights on the dash go out when the centre panel lights etc go out also.

**Comment by Tekada1-0** [comment]
The main engine generators go off line  at 95%.  If you pull the engines to idle at any time you need to start the APU and turn on the APU generator first or you will lose electrical power.  

I'm going to try and replicate this bug as you describe.

**Comment by CarlBevan** [comment]
Ok that may be why it is happening. Sorry for the confusion.

Loving the mod, keep up the great work.
