### ISSUE TITLE
Stabilator Manual Slew inverts Stabilator Auto On/Off keybindings when Stab Auto is enabled

### ISSUE THREAD

**Issue by Alighierian** [Kinkkujuustovoileipa/uh-60l#133]
First observed in Syria Multiplayer in version 1.1, but replicated in Caucasus Free Flight instant action. Resetting keybindings (by means of disabling the existing folder and creating a new one) had no effect. Hot or cold start doesn't appear to affect it either.
The friend I was playing with experienced the same bug when I walked him through the steps.

I can replicate it at will, and it behaves the same way every time:
- Stabilator Auto set to ON
- Stabilator Manual slew either up or down, can be done via keybinding or cockpit click
- Stabilator Auto turns OFF and stabilator position is adjusted according to input
- Keybinding effects for Stabilator Auto - ON and Stabilator Auto - OFF are inverted: 
ON turns it off, and OFF turns it on. Persists until Stab Manual Slew is operated again with Stab Auto turned on. No inverting occurs when Stab Auto is turned off.

---

Convo from discord with Bailey - bug-report channel:

Alighierian — Today at 20:59
Not sure if this is just something wonky on my end, just noticed it:
The keybinding for for 'Stabilator Auto - OFF' and 'Stabilator Auto - ON' are currently inverted for me, with the OFF-binding turning it on, and vice versa for ON.
It appears to switch around when Stabilator manual DOWN (momentary) is tapped
but it only switches when I enable the Stab auto again, instead of inverting it every time
Bailey — Today at 21:01
It looks like you may some conflicting files. Backup your ...\Saved Games\DCS.openbeta\Config\Input\UH-60L folder and then delete the original folder. Restart DCS and try again.
If that does not work, a detailed bug report on the git will be be greatly appreciated. This one is interesting.
Alighierian — Today at 21:03
Will do. Currently in multi with a buddy, so I'll look into it further when we're done.
Bailey — Today at 21:03
That fact would be good to add too.
Alighierian — Today at 21:09
My buddy appears to have the same, and I can replicate with by manually operating the Stab Manual Up/Down triangle, regardless of up or down used
Bailey — Today at 21:11
The switch switches. Does the stab indicator match the physical switch position?
Alighierian — Today at 21:13
The switch itself appears to properly send the stab up/down respective of which direction is applied
Bailey — Today at 21:15
Please report that. Looking forward to what the devs see.
You can attach this convo.

**Comment by asherao** [comment]
I can replicate the issue. I believe it has to do with the logic that turns the light "off".

**Comment by sniporbob** [comment]
The pull request will fix the inversion of the stab auto - on and stab auto - off command. However, for reasons I do not understand, issuing the same command consecutively will not work. This means you cannot press stab auto - on, then manually slew the stab, then press stab auto - on again. The second stab auto - on is effectively ignored. It will only update if you press stab auto - off, then stab auto - on.

This should be revisited in the future to figure out why issuing the same command more than once gets ignored.

**Comment by sniporbob** [comment]
Ok this has been revisited (an entire 15 minutes later lol) after suddenly thinking of something to try. Problem fully resolved. Everything working properly now.
