### ISSUE TITLE
AFCS advisory brightness

### ISSUE THREAD

**Issue by Jedi1-4** [Kinkkujuustovoileipa/uh-60l#143]
In sunlight the advisories are difficult to see. In pictures only the trim is turned off. pictures are taken from different angles.

![Screen_220130_120049](https://user-images.githubusercontent.com/98358215/151715664-5c550b3c-5198-43bd-9c4d-47cda9c2e776.png)

**Describe the bug**
![Screen_220130_120036](https://user-images.githubusercontent.com/98358215/151715662-1d3f8303-4dfb-4503-b2a6-877a096129ed.png)

![Screen_220130_120052](https://user-images.githubusercontent.com/98358215/151715666-4638fbd1-fc49-449a-af3d-51d620a1d871.png)

**Comment by asherao** [comment]
You didn't even follow the template format :D I too have noticed this when playtesting a number of missions back to back.

**Comment by Jedi1-4** [comment]
I'll get some pics of AFCD on a sunny day. If we every have one here again. ;)

**Comment by Jedi1-4** [comment]
Checked. It mostly dissapears in actual as well in direct sunlight.
