### ISSUE TITLE
ADF and VOR audio

### ISSUE THREAD

**Issue by Jedi1-4** [Kinkkujuustovoileipa/uh-60l#162]
ADF audio should only be heard if NAV switch on the ICS control is switched to ON. Currently with switch in either position audio from station is heard.

VOR/LOC audio should only be heard if AUX switch on ICS control is switched ON. Currently with switch in either position audio from station is heard.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Can you help develop this feature? How?**
Describe what you can do to make this feature become real. Providing information, formatted luas, or other resources.

**Additional context**

**Comment by Kinkkujuustovoileipa** [comment]
Known, but cannot be implemented due to limitations of modding - not currently possible to set volume or on/off on radio receivers at this time. Will be fixed if becomes possible. In 1.2 the switches will default to ON state.
