### ISSUE TITLE
External Cargo Emergency Unhook and External Cargo Autounhook not working.

### ISSUE THREAD

**Issue by domi-domi** [Kinkkujuustovoileipa/uh-60l#177]
Bindings work within the controls page (i.e. clicking assigned button makes selector jump to the respective line), but the slung load remains attached. 

Tested with pre-spawned loads, selected via the All Cargos F-button menu. Hooking up sling works as expected, though crew chief callouts aren't there.

**Comment by Kinkkujuustovoileipa** [comment]
Can't fix, mod limitation. Go annoy ED about it.
