### ISSUE TITLE
Add Internal Cargo so that Embarking/Disembarking mission editor commands work

### ISSUE THREAD

**Issue by robgrahamau** [Kinkkujuustovoileipa/uh-60l#198]
Currently despite being able to be given the Transport task the EMBARK/DISEMBARK options are not avalible because the UH-60L.lua file is missing any reference to 'internal cargo'

A simple addition of 

```
	InternalCargo = {
			nominalCapacity = 2400,
			maximalCapacity = 2400,
		},
```

or simular will allow the carrying of AI troops with out the need for CTLD or other mods.

**Comment by Kinkkujuustovoileipa** [comment]
Hi, thanks for this, will add and test!

**Comment by cerealexfpv** [comment]
How is going? This would be amazing!

**Comment by Kinkkujuustovoileipa** [comment]
Added for 1.3
