### ISSUE TITLE
VRS - too rapid onset; too gentle descent

### ISSUE THREAD

**Issue by Kinkkujuustovoileipa** [Kinkkujuustovoileipa/uh-60l#2]
VRS is onsetting too rapidly and in too gentle descents. Steeper descents should be possible with less risk of a stall.

**Comment by asherao** [comment]
VRS onset seems to be less "snappy". Can better save VRS conditions. Would be good to get input from those with more experience.

**Comment by rotordisc-jockey** [comment]
> VRS onset seems to be less "snappy". Can better save VRS conditions. Would be good to get input from those with more experience.

Have you found some SME's to advise on this? To be honest, it can be as snappy as you like - but consider having that onset at circa 2000ft/min for an empty aircraft. Even at higher AUM, power limits should be more of a threat that VRS to be honest...

**Comment by mlawson1217** [comment]
Fixed, and closing for now. Can tune further later if needed, but see no issue currently.
