### ISSUE TITLE
Stabilator Incorrect Cruise Trim Position

### ISSUE THREAD

**Issue by ftr784** [Kinkkujuustovoileipa/uh-60l#200]
Problem:
The stabilator should be between 0° and 4° down during normal cruise.  Currently the stabilator slews to approximately 7° up during cruise.  The stabilator should only automatically slew above 0° during autorotations and certain turbulence conditions.

Reference:
You can find the various values in Chapter 2 of the MTF pub.

**Comment by Kinkkujuustovoileipa** [comment]
Redone with accurate position calculations based on data available.
