### ISSUE TITLE
AN/ARC-186 tuning issue

### ISSUE THREAD

**Issue by bfarmsbob** [Kinkkujuustovoileipa/uh-60l#201]
In order to use manually tuned frequencies, instead of the 'man' ( manual) position,  the selector must be placed in the 'pre' position (preset}.  There is no functionality for using presets

**Comment by Cactus8593** [comment]
to add to it, the FM, AM &  MAN are tuned to 121.5, and the PRE is grabbing the the numbers off the dial knobs
