### ISSUE TITLE
Missing file 'DCS-SimpleRadioStandalone.lua' in v1.3 ZIP file....

### ISSUE THREAD

**Issue by FrankyEverest** [Kinkkujuustovoileipa/uh-60l#203]
Just reporting...

The file named 'DCS-SimpleRadioStandalone.lua' for SRS users is missing in the latest Blackhawk v1.3 ZIP file.  Does that mean we can keep using the .lua file supplied in the v1.2 version of the Blackhawk?

Thanks for clarifying...

**Comment by MrPixelGlitch** [comment]
In Version 1.3 the '_DCS-SimpleRadioStandalone.lua_' file got removed as it isn't necessary anymore with version 2.0.0.0 and above of SRS
