### ISSUE TITLE
pds 

### ISSUE THREAD

**Issue by monseigneur06** [Kinkkujuustovoileipa/uh-60l#213]
hello guy ! 

i just ask if it's possible to get the pds for reskin the uh-60l ?

thanks a lot 

merci =)

**Comment by Cactus8593** [comment]
as stated on the discord "#Liveries" dated 01/17/2022...not until the update to the model is completed...
here's the unofficial template until then...
disscussion link... https://discord.com/channels/776815105810759701/932681798364840017/936797789143322694
Template link... https://drive.google.com/file/d/1PSfvdoIKQnJnoK7FTJYpmMD65aHxrq0T/view
