### ISSUE TITLE
Give the Mod a DCS GUI Icon, as it currently gets a generic DCS icon.

### ISSUE THREAD

**Issue by rudel-chw** [Kinkkujuustovoileipa/uh-60l#217]
**Is your feature request related to a problem? Please describe.**

It's not a problem, but I believe having a personalized GUI Icon instead of a generic one, gives the Mod a more polished appearance.

**Describe the solution you'd like**
Use the current Discord channel Icon, as a DCS Icon.

**Describe alternatives you've considered**
I tried to add the Icon myself, but its beyond my modding abilities.

**Can you help develop this feature? How?**
No, sorry.

**Additional context**
I have added a screenshot where the UH-60L Mod appears using a generic Icon:

![UH-60 Icon](https://user-images.githubusercontent.com/51679833/176483186-ad26fb07-78d9-425e-bc05-7f0fe818b375.jpg)

**Comment by Norsk22771** [comment]
Already fixed. Closing.
