### ISSUE TITLE
AN/ARC-201 frequency step size too large

### ISSUE THREAD

**Issue by sniporbob** [Kinkkujuustovoileipa/uh-60l#222]
The radio should have a frequency step size of 5khz. It is currently configured with a step size of 25khz, which does match limitations of entering frequencies via keypad. Using OFST, however, the radio should be adjustable in 5khz increments.

**Comment by MrPixelGlitch** [comment]
Where do you have your information from that it should be adjustable in 5kHz increments?

The radio manufacturers datasheet states following information:
"30-88 MHz VHF-FM" "2,320 channels"

From this information the spacing is calculated -> 
88MHz-30MHz = 58MHz Range
Now divide 58MHz Range by 2320 Channels = 0.025 MHz spacing (= 25 kHz)

**Comment by sniporbob** [comment]
My information comes from two sources:
1) I own one (the manpack version). Picture attached demonstrating a 5khz offset.

![IMG_20220820_231742155 - Copy](https://user-images.githubusercontent.com/8404483/185778566-32cd2cea-7754-487a-8507-9ab67f9ec86b.jpg)


2) TM 11-5821-333-12 specifically section 2-16 which states that frequencies can be offset by 5 or 10 kHz. The pdf is available here and you'll find the offset info on pdf page 39: https://radionerds.com/images/2/2b/TM_11-5821-333-12.PDF

You're correct that the channels have to be entered in 25khz increments. The radio will not let you manually punch in a frequency that is not a multiple of 25khz. This restriction in spacing only applies when typing in the frequency. After entering a frequency you can then use the offset functionality to adjust the frequency up or down by any of the following amounts: -10khz, -5khz, +5khz, +10khz. You can effectively tune to any 5khz increment by selecting the right base frequency and offsetting as appropriate. As an example:
30.000MHz + 00kHz = 30.000MHz
30.000MHz + 05kHz = 30.005MHz
30.000MHz + 10kHz = 30.010MHz
30.025MHz - 10kHz = 30.015MHz
30.025MHz - 05kHz = 30.020MHz
30.025MHz + 00kHz = 30.025MHz


I've actually finished the code and implemented all of this on the radio itself, but there's something going on behind the scenes in some other part of the module that is rounding the frequency to 25kHz increments, which prevents SRS from operating on the frequency specified by the offset. I've had no luck tracking down the source of this issue.
