### ISSUE TITLE
Armed Blackhawk

### ISSUE THREAD

**Issue by SteelersForever** [Kinkkujuustovoileipa/uh-60l#227]
**Is your feature request related to a problem? Please describe.**
Many in the community want an Armed Blackhawk. However, you do not have it in your base UH-60L, so we have to use this mod:
https://www.digitalcombatsimulator.com/en/files/3326421/

**Describe the solution you'd like**
I would like to have the Armed Blackhawk mod included in the UH-60L until you can make a better Armed Blackhawk.

**Describe alternatives you've considered**
I have installed it, but many people might have trouble installing the Armed Blackhawk mod, and they might not even know about it.

**Can you help develop this feature? How?**
To install the mod, you take the files in it and replace a bunch of base UH-60L files with it. You do this with the Miniguns mod too that you need to install before the Armed Blackhawk. However, this doesn't break IC, so this interim solution could help.

**Additional context**
![image](https://user-images.githubusercontent.com/122119544/213220004-6517b8f0-830e-40d1-b4a1-8571636fd59f.png)

**Comment by Norsk22771** [comment]
UH-60L main mod will be without any armaments for now.
