### ISSUE TITLE
APR39 emitter type bug

### ISSUE THREAD

**Issue by Lynx13D** [Kinkkujuustovoileipa/uh-60l#228]
RWR vocalizer always says "SA SA UNKNOWN" no matter what SA type launcher is tracking or shooting

the problem is in APR39.LUA
`function getSAMType(samData)
    local samType
    if samData.unit_type_sym:get() == "a8" then`

It should be checking for 8a, 10a and so on for all the following entries
works fine if check for 8a when being tracked by Sa-8 for instance

**Comment by Lynx13D** [comment]
fixed script itself
[APR39_typefix.zip](https://github.com/Kinkkujuustovoileipa/uh-60l/files/10511294/APR39_typefix.zip)

**Comment by Norsk22771** [comment]
Will take a look at it. Thanks for the report.
