### ISSUE TITLE
APR39 sound file error

### ISSUE THREAD

**Issue by sniporbob** [Kinkkujuustovoileipa/uh-60l#235]
ED_SOUND (Main): source_add(host:COCKPIT, proto:APR39/ap39failure, alt_proto:): can't find proto

The above error is seen in the dcs logs. It is due to a misspelling of apr39failure (it was spelled ap instead of apr). The files containing this typo are:

Cockpit/Scripts/APR39/device/tables.lua
line 131

Cockpit/Scripts/Systems/sound_system.lua
line 61

**Comment by Norsk22771** [comment]
Fixed in merged pull request #239
