### ISSUE TITLE
Headings and Bearings are generally 'true' not 'magnetic'

### ISSUE THREAD

**Issue by shearn89** [Kinkkujuustovoileipa/uh-60l#248]
**Describe the bug**
Headings and bearings to waypoints/instruments are in true heading not magnetic heading, meaning that you end up not at where you intended when following the Nav cues.

**To Reproduce**
1. Open the attached `UH60-test` mission.
2. open F10, click aircraft to see route
3. Use the ruler to measure bearing from ownship to waypoint - should be 303 mag, 310 true
4. Observe DGNS and AVS7 both show bearing to WPT1 as 310

**Expected behavior**
Instruments should all be in magnetic, from the AHRS

**Media**
[UH60-test.zip](https://github.com/Kinkkujuustovoileipa/uh-60l/files/13174545/UH60-test.zip)

**Comment by shearn89** [comment]
Will attempt to fix myself.

**Comment by twanmal** [comment]
I already corrected the bug in a previous version.

**Comment by shearn89** [comment]
Must have got unfixed or lost in a previous merge I guess.
