### ISSUE TITLE
Suggestion: Add flare dispenser

### ISSUE THREAD

**Issue by Eule22TBone** [Kinkkujuustovoileipa/uh-60l#25]
For the flight and mission profile of the Blackhawk, a flare dispenser is necessary since chaffs are useless against IR missiles.

For example:
![1](https://user-images.githubusercontent.com/40805078/150638403-961f1d42-0e77-4cc3-81ed-6d8cee507267.jpg)
![2](https://user-images.githubusercontent.com/40805078/150638405-70dcb645-06f6-4a24-8dcf-dfa7cac6bbf4.jpg)

**Comment by Kinkkujuustovoileipa** [comment]
Will be added, remains to be seen if for 1.1 though
