### ISSUE TITLE
ILS Course Deviation Pointer Is Opposite Steering

### ISSUE THREAD

**Issue by asherao** [Kinkkujuustovoileipa/uh-60l#30]
"The pilot must fly into the needle to regain on-course track" -10 2.80.1.5
Observed on Andersen and Kobuleti airports. Repeatable. https://youtu.be/SH5n2sQIb7s

**Comment by Kinkkujuustovoileipa** [comment]
Video isn't clear enough to understand the problem.

**Comment by asherao** [comment]
- Set up a mission where the aircraft is left of the runway, but on final
- Active pause on mission start
- Enter ILS course and frequency
- Engage ILS mode
- In game the needle points left, commanding you to turn away from the runway. 

Because you are on the left side of the runway, according to -10 2.80.1.5 the needle should be pointing right to get you back on course.

**Comment by asherao** [comment]
Note, it may effect other modes. Have not confirmed. 
![image](https://user-images.githubusercontent.com/15984377/150672774-4eef1d00-882a-438d-813d-6ee6cce236a9.png)

**Comment by asherao** [comment]
I think that the game behavior is confirmed inaccurate for all modes. 
![image](https://user-images.githubusercontent.com/15984377/150672931-62c1ea05-7186-4ee4-a0e4-2fa87fd79628.png)
![image](https://user-images.githubusercontent.com/15984377/150672917-c8216340-32bc-4798-b592-60d2eacd3b50.png)

If I dial a course more than 000 I should have to steer left to intercept the radial. According to the -10, I should get a left needle. In game it is giving me right needle.

Similar can be seen here. 
![image](https://user-images.githubusercontent.com/15984377/150673061-8faaddac-10db-4907-8433-e26f1bf6054f.png)

![image](https://user-images.githubusercontent.com/15984377/150673052-3520195d-4692-4828-92a5-4cd492506548.png)

**Comment by Kinkkujuustovoileipa** [comment]
The course needle just tells you the course direction - it's no different from the heading bug in that regard. As for the last picture, you are in heading submode so you're being commanded to your heading bug, not to intercept the radial.
I think there is some confusion here so we can discuss on comms when you're available.

**Comment by asherao** [comment]
Fixed
