### ISSUE TITLE
HUD brightness switchs 

### ISSUE THREAD

**Issue by CoastieJeff** [Kinkkujuustovoileipa/uh-60l#31]
Not sure if this is a bug, or I'm just setting it up wrong, but the HUD dim and brightness buttons don't seem to have incremental adjustability. When I bind a key to the HUD 'up' and 'down' brightness functions, it goes all the way up to full, or dims down to off with a singe button press. Not just a little at a time to allow fine-tune brightness adjustment. Thanks.

**Comment by SnappyComebacks** [comment]
Elaborating more on this:
When using the keybinds for the AN/AVS-7, the related cockpit switch does not return to center.  So once you press `AN/AVS-7 Brighten` or `AN/AVS-7 Dim`, the switch will stay in the up or down position.  To get around this you have to use the mouse to return to center.

**Comment by asherao** [comment]
Currently the return to center is fixed for increase. Decrease keybind does not work at all.

**Comment by Jedi1-4** [comment]
Confirmed fixed. Switch operates as normal when mapped.
