### ISSUE TITLE
RCS problem about the UH60 mod

### ISSUE THREAD

**Issue by tdk647** [Kinkkujuustovoileipa/uh-60l#32]
Hi,
I'm from a virtual flight group team, when we were conducting a large flights mission on DCS, something weird just happened.

Our F-16 player shot a AIM120 to a bandit in 3nm, the bandit went to notch, and the AIM-120 turned away to finally hit our UH60 player behind the bandit about 6 miles, this blue on blue incident made we do a test, and turned out that when AIM120 was fired at maddog mode, it would capture the Blackhawk rather than IL-76. In another word, BlackHawk seems to be at a higher priority to AIM120 seeker.

So we are wondering if there's any reason for this, such as the RCS problem or others. Or maybe someone can tell me whether this is caused by DCS itself or only would happen to this mod.

looking forward to reply, thanks

![QQ图片20220123022129](https://user-images.githubusercontent.com/68233715/150650877-d22228b3-0996-4d0b-b09d-a25e5522cd5e.png)
!

**Comment by Kinkkujuustovoileipa** [comment]
Mod has the same RCS (10m2) as the AI UH-60A. The IL-76 has a much higher RCS (80m2). I suspect this is mostly DCS being DCS.

**Comment by tdk647** [comment]
> Mod has the same RCS (10m2) as the AI UH-60A. The IL-76 has a much higher RCS (80m2). I suspect this is mostly DCS being DCS.

Cool, and by the way I will appreciate if more control settings are added. Many button can only be clicked by mouse and that is not so convenient for VR users.

**Comment by Kinkkujuustovoileipa** [comment]
I am a VR user, it's 100% convenient for me ;)
Of course, we are adding more bindable controls in the coming update :)

**Comment by Memphis291** [comment]
I´m VR user too and try to use as much as possible in Cockpit Buttons...thats what DCS VR makes it so immersive.

**Comment by tdk647** [comment]
> I´m VR user too and try to use as much as possible in Cockpit Buttons...thats what DCS VR makes it so immersive.

Yeah I totally understand, but many of us are building our own simulation environment, including some ufc and mfd panel, so more bindable controls would help a lot. Thanks, it's a great mod, we quite enjoy it.
