### ISSUE TITLE
HUD color options

### ISSUE THREAD

**Issue by CoastieJeff** [Kinkkujuustovoileipa/uh-60l#33]
Have the ability to alter HUD colors (green, yellow, red, etc.) to allow for better HUD contrast while operating in different environments and lighting conditions.

**Comment by Kinkkujuustovoileipa** [comment]
Sorry, AFAIK the AVS-7 only comes in green, since it's designed for NVG use only. Fixing the brightness/dimming should help this.

**Comment by CoastieJeff** [comment]
Ahh, gotcha. OK, thanks.

No worries.


Jeff Lucas

________________________________
