### ISSUE TITLE
External sound bug

### ISSUE THREAD

**Issue by NJanika** [Kinkkujuustovoileipa/uh-60l#34]
I hear the A-10 engine roaring in all external views. The rotor blades sound almost gone.
The sound looks good in the cockpit.

**Comment by NJanika** [comment]
Thank you for the great work!

**Comment by mlawson1217** [comment]
Dependency on sound file for rotor sound from other mod fixed. Closing for now.

Note: A10 audio bug is still being investigated and is in separate issue.

**Comment by NJanika** [comment]
Hello!
I'm owerwriten my sdef folder with the (new?)sdef from the discord and it
works!
I din't do anything with the xeng.waw file.
I don't hear the A10's engine sound anymore.

Matt Lawson ***@***.***> ezt írta (időpont: 2022. jan. 27.,
Cs, 20:43):
