### ISSUE TITLE
Aircraft too fast, too rapid acceleration

### ISSUE THREAD

**Issue by Kinkkujuustovoileipa** [Kinkkujuustovoileipa/uh-60l#4]
Should be topping out around 150 with some vibration at that speed. Acceleration much too fast.

**Comment by asherao** [comment]
Accel is slower. 
Vibes start at about 150.
Top speed on Caucasus Instant Start is about 185kts at 200 AGL via F2 view. 
Can no longer "jump" into the air by rapidly increasing collective on takeoff.

**Comment by mlawson1217** [comment]
Fixed
