### ISSUE TITLE
HUD Changes to "36" when approaching "N"

### ISSUE THREAD

**Issue by asherao** [Kinkkujuustovoileipa/uh-60l#43]
When on headings very close to north the hud indication "N" changes to "36". At the same time the numbers along the same tape will shift. When transitioning to heading not near north the tape will turn back  to "normal".

**Comment by asherao** [comment]
"N" changes to "36" is fixed. Number jumping/shifting remains.

**Comment by Kinkkujuustovoileipa** [comment]
Won't fix shifting, is minor.
