### ISSUE TITLE
HUD Bearing to Waypoint Pointer "V" behavior 

### ISSUE THREAD

**Issue by asherao** [Kinkkujuustovoileipa/uh-60l#44]
The Bearing to Waypoint Pointer cursor should invert "V" when helicopter is
moving away from waypoint. It currently does not in-game.
Source: -10 Table 4-1 No. 2

**Comment by Kinkkujuustovoileipa** [comment]
It's based on relative heading so I guess that's accurate

**Comment by mlawson1217** [comment]
fixed
