### ISSUE TITLE
HUD Radar Altitude (AGL) Readout Formats

### ISSUE THREAD

**Issue by asherao** [Kinkkujuustovoileipa/uh-60l#45]
Source: -10 Table 4-1 No. 12

- [X] 0 - 200 feet, 1 foot units
- [x] 200 - 1000 feet, 10 foot units (currently 1 foot units)
- [ ] disappears above 999 feet, and reappears below 950 feet (currently reappears below ~1000 feet)

**Comment by asherao** [comment]
Brief flash at 1000ft while passing 1000ft during climb. I would have not expected this according to the manual. I would expect 990 to disappear at 999ft. 

- [X] 200 - 1000 feet, 10 foot units (currently 1 foot units)

**Comment by Kinkkujuustovoileipa** [comment]
Picky but should be fixed

**Comment by asherao** [comment]
Yes, quite picky. Low priority in my mind. Has not yet been fixed. 
![image](https://user-images.githubusercontent.com/15984377/151081767-d5950d1d-4182-4f7a-b1bd-b4773588af73.png)

**Comment by mlawson1217** [comment]
RDR Altitude on HUD Turns off above 999 correctly, but never comes back on. You do get a blinking box where the number would be when you get low again.

**Comment by Jedi1-4** [comment]
Fix confirmed. It comes back on below 950
