### ISSUE TITLE
Pitch Axis in Controls Indicator Reversed

### ISSUE THREAD

**Issue by airframe26** [Kinkkujuustovoileipa/uh-60l#48]
The pitch axis in the Controls Indicator is reversed. The roll axis is working fine.

**Comment by asherao** [comment]
I see the same. Pulling back (nose up) makes the indicator go up. On the contrary for the A-10A pulling back (nose up) will make the indicator go down.

**Comment by asherao** [comment]
Fixed in mod v1.1
