### ISSUE TITLE
Radios only work with Easy Comms enabled

### ISSUE THREAD

**Issue by Kinkkujuustovoileipa** [Kinkkujuustovoileipa/uh-60l#5]
Radios should work without easy comms

**Comment by asherao** [comment]
Cannot open comms menu while airborne with easy comms disabled.
Can open comms menu on ground with easy comms disabled. Unable to fully test.
Tested on Caucasus Free Flight, Air-to-Air Refueling, and two custom ME missions with air starts.

**Comment by Kinkkujuustovoileipa** [comment]
Accidentally overwrote the key binding for the new radios with your bindings :D fixing for next RC
