### ISSUE TITLE
HUD Barometric Altitude shows more than 20,000 ft

### ISSUE THREAD

**Issue by asherao** [Kinkkujuustovoileipa/uh-60l#50]
Source: -10 Table 4-1 No. 7 
-1000 to 20,000 feet

HUD currently shows more than 20,000ft. Can use ME to set aircraft at ~18,000ft. Fly above 20,000ft to see bug.
![image](https://user-images.githubusercontent.com/15984377/150672509-af4e69ad-a7b6-42a1-ab61-fa22bdbbfee3.png)
![image](https://user-images.githubusercontent.com/15984377/150672591-0fc336e3-5548-435b-afd7-df87ba07a4b5.png)

**Comment by asherao** [comment]
having difficulty climbing above 11,000 ft. Cannot test at this time.

**Comment by Kinkkujuustovoileipa** [comment]
Spawn higher?

**Comment by asherao** [comment]
> Spawn higher?

Cant due to what I believe is ME limits for heli spawn height.

**Comment by asherao** [comment]
Issue is fixed.
