### ISSUE TITLE
Search light 

### ISSUE THREAD

**Issue by mange70** [Kinkkujuustovoileipa/uh-60l#51]
You can’t see on the advisory panel that the search light is on or of..
Landing light works.
A little faster slewing on the lights would be nice…
Thanks for a great mod.

**Comment by asherao** [comment]
Fixed. Rate seems to be increased. 
![image](https://user-images.githubusercontent.com/15984377/150833830-02ec8302-b939-4eee-8f50-46436c2ca0be.png)
