### ISSUE TITLE
Different Multicrew desyncs (described below)

### ISSUE THREAD

**Issue by KingSharkoon** [Kinkkujuustovoileipa/uh-60l#55]
I know Multicrew is WIP - but i just want you to tell which issues we could find for futher development:

- Fuel Shutoff Lever (The ones with the white ball) are not synced between Host and Client
- Doors are not synced (have to open and closed by each crewmember)
- Panel Test (Master Light Test) Switch not synced
- Radar Altimeter turned on not synced (Stays off for the other crew member and has to be turned on on both sides by each crewmember)
- Throttle Lever are not synced (One stays in OFF even if both are set to IDLE)

**Comment by Kinkkujuustovoileipa** [comment]
I will do some testing but am not committing to a fix
