### ISSUE TITLE
VSI Roll Command based on Heading not on Track

### ISSUE THREAD

**Issue by Kinkkujuustovoileipa** [Kinkkujuustovoileipa/uh-60l#7]
VSI roll command bar calculates using aircraft heading not the track angle, so is incorrect when crabbing e.g. in crosswind approaches

**Comment by mlawson1217** [comment]
I think that this is working but will test further. Hard to tell.

**Comment by asherao** [comment]
Tested with 20 and 40 kt winds. Fixed. https://youtu.be/AfCsDll_-_E
