### ISSUE TITLE
Turning CIS Heading mode ON disables SAS1

### ISSUE THREAD

**Issue by Teowarn** [Kinkkujuustovoileipa/uh-60l#70]
When I turn the CIS heading mode ON - then SAS1 is automatically turned off. SAS1 can't be turned on manually while the CIS heading mode is on. 

When CIS heading mode is turned off, SAS1 automatically restores its previous state (turns on if it was like that before CIS heading mode was activated).

**Comment by asherao** [comment]
SAS1 maintains state when CIS Heading mode is toggled. Fixed.
