### ISSUE TITLE
Braking force during roll on.

### ISSUE THREAD

**Issue by Jedi1-4** [Kinkkujuustovoileipa/uh-60l#75]
Braking force is too weak during a roll on. Should stop in approx. half the distance

**Comment by Kinkkujuustovoileipa** [comment]
Just to clarify - this is wheel brakes? Or a full pullback on the cyclic?

**Comment by Jedi1-4** [comment]
Wheel brakes. They work really well but can overheat if too aggressive.

**Comment by Jedi1-4** [comment]
Working normal in version 1.2.
