### ISSUE TITLE
PDU press to test

### ISSUE THREAD

**Issue by Jedi1-4** [Kinkkujuustovoileipa/uh-60l#77]
When the PDU test switch is pressed you should see all 8s in the digits widow.

**Comment by Kinkkujuustovoileipa** [comment]
![image](https://user-images.githubusercontent.com/73441823/150883589-fc80b5be-ad7f-47d1-acce-33c74776762f.png)
Says 188 here, which is still different from 111 - can't remember where I got that from in the first place. Can you confirm?

**Comment by Jedi1-4** [comment]
Thats right. Im getting old :)

**Comment by asherao** [comment]
displays 188 188 when test is held. Both seats tested. Fixed.
