### ISSUE TITLE
Stabilator Auto Control Mode should be on during startup.

### ISSUE THREAD

**Issue by Tekada1-0** [Kinkkujuustovoileipa/uh-60l#81]
Stabilator auto control mode will turn on automatically when the APU GEN is turned on during startup.  The stabilator if in the up position will program full down upon application of power to the system (apu gen on). 

Cyclic mounted slew switch, and manual slew switch if actuated will override and turn off the automatic control mode.  
The stabilator will slew with either switch as long as they are held.  
Automatic control mode is re-enabled by pressing the auto mode button the AFCS control panel.

**Comment by asherao** [comment]
- [x] Stabilator auto control mode will turn on automatically when the APU GEN is turned on during startup. 
- [x] The stabilator if in the up position will program full down upon application of power to the system (apu gen on).
- [x] Cyclic mounted slew switch, and manual slew switch if actuated will override and turn off the automatic control mode.
- [x] The stabilator will slew with either switch as long as they are held.
- [x] Automatic control mode is re-enabled by pressing the auto mode button the AFCS control panel.

Fixed.
