### ISSUE TITLE
Tail wheel switch label and operation.

### ISSUE THREAD

**Issue by Jedi1-4** [Kinkkujuustovoileipa/uh-60l#82]
IRL.  Tail wheel lock switch defaults on (LOCK) during start up. when pressed it goes blank during tail wheel pin movement then (UNLOCK) when pin is out. maybe 1 to 2 seconds for transition.

**Comment by asherao** [comment]
Tail wheel lock switch defaults on (LOCK) during start up. When pressed it goes blank for about 2 seconds. UNLK appears. Fixed.
