### ISSUE TITLE
Clock time runs beyond 2400

### ISSUE THREAD

**Issue by Jedi1-4** [Kinkkujuustovoileipa/uh-60l#86]

**Comment by asherao** [comment]
![image](https://user-images.githubusercontent.com/15984377/151139417-6db70b4d-1d40-40fc-a4fd-ec6ba309c07b.png)

![image](https://user-images.githubusercontent.com/15984377/151139477-fa313379-acc6-4694-8049-00105b9ab6cb.png)

Confirmed.

**Comment by asherao** [comment]
![image](https://user-images.githubusercontent.com/15984377/151143021-fff4cacc-ab86-41ab-88ad-060b877fef01.png)

**Comment by mlawson1217** [comment]
Clock reverts to 00:00:00 after 23:59:59. Closing.
