### ISSUE TITLE
Battery low caution

### ISSUE THREAD

**Issue by Jedi1-4** [Kinkkujuustovoileipa/uh-60l#88]
Battery low caution came on after approx. 45 mins of flight time.

**Comment by asherao** [comment]
Looking into cockpit_params, it seems that the batteries are not recharged after a normal start. Therefore they continuously drain.

**Comment by mlawson1217** [comment]
Bat low charge light came on after about 13 minutes.

**Comment by mlawson1217** [comment]
Battery low charge warning came on after about 13 min of battery only. Battery died at about 14 minutes.

**Comment by mlawson1217** [comment]
Fixed. Low charge came on after 12 min of batt only, turned on APU and APU gen for a few minutes, low charge light went out near immediately, and then turned off APU gen (not APU) and light came back after a few minutes. Closing issue.
