### ISSUE TITLE
Sound issues in the A10

### ISSUE THREAD

**Issue by Delta7I** [Kinkkujuustovoileipa/uh-60l#90]
https://user-images.githubusercontent.com/93885105/151097580-acc68f4d-e3be-4c24-93ee-3dfcba01fac4.mp4

https://user-images.githubusercontent.com/93885105/151097583-4d0a0240-f49b-4ff6-9387-7db05b9ab915.mp4

**Comment by Jonny-03** [comment]
https://github.com/Kinkkujuustovoileipa/uh-60l/issues/71#issue-1113137065

**Comment by Tekada1-0** [comment]
Delta71, 
Can you post a screen shot of your Audio Settings from in game.  I want to replicate this to identify the bug. Do you have any other mods installed?

**Comment by Delta7I** [comment]
Nope

**Comment by Delta7I** [comment]
> Delta71, Can you post a screen shot of your Audio Settings from in game. I want to replicate this to identify the bug. Do you have any other mods installed?

![Digital Combat Simulator  Black Shark Screenshot 2022 01 27 - 22 19 56 64](https://user-images.githubusercontent.com/93885105/151428853-68f748ea-f662-4fe6-83d5-cf8e7dd6dd8a.png)

**Comment by Delta7I** [comment]
> Delta71, Can you post a screen shot of your Audio Settings from in game. I want to replicate this to identify the bug. Do you have any other mods installed?

![Digital Combat Simulator  Black Shark Screenshot 2022 01 27 - 22 19 56 64](https://user-images.githubusercontent.com/93885105/151429151-d6bc9769-05fd-4cbd-8493-86c4971e0c9a.png)

**Comment by Targanon** [comment]
can confirm I have had that too!
