### ISSUE TITLE
AHRU lights (ALN, SLAVE, etc...) only light up if the Lower Console Lights Switch is turned up.

### ISSUE THREAD

**Issue by Jonny-03** [Kinkkujuustovoileipa/uh-60l#92]
Correct me if it is like that in the real aircraft.

**Comment by Kinkkujuustovoileipa** [comment]
This is based on the behaviour in the real aircraft. It's absolutely insane to me, but that's the way it is.

**Comment by Jonny-03** [comment]
Ok thanks for responding. (Pretty insane yeah)
