### ISSUE TITLE
Radar Altitude on HMD brightness doesn't adjust

### ISSUE THREAD

**Issue by mlawson1217** [Kinkkujuustovoileipa/uh-60l#93]
Radar Altitude on HMD brightness doesn't adjust with the rest of the HMD.

**Comment by mlawson1217** [comment]
bar doesn't disappear when all the way dimmed

**Comment by Jedi1-4** [comment]
After changing HUD brightness the altitude bar brightness does not change until you go above 200 or land and then fly back intyo the bars range. Also, the bar still remains on when hud is dimmed all the way down.

**Comment by asherao** [comment]
![image](https://user-images.githubusercontent.com/15984377/151557108-330a7b9a-5c41-4924-be46-86fee81decd9.png)
