### ISSUE TITLE
Starter drop out

### ISSUE THREAD

**Issue by Jedi1-4** [Kinkkujuustovoileipa/uh-60l#98]
Engine starters should not drop out prior to 52% NG per manual.    52-65 range   around 58% is good average IRL.

**Comment by mlawson1217** [comment]
Drops out immediately one advanced to ground idle. Not fixed in SF 2, but may be in internal version.

**Comment by Jedi1-4** [comment]
Checked out ok

**Comment by asherao** [comment]
Starter light goes out around 58% Ng. Fixed.
